"""Fixed column requirements in promo table.

Revision ID: bcf9ccf9ab0b
Revises: 6ab426bd46ab
Create Date: 2026-09-22 15:32:50.936490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf9ccf9ab0b'
down_revision = '6ab426bd46ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_code', schema=None) as batch_op:
        batch_op.alter_column('sponsor',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_code', schema=None) as batch_op:
        batch_op.alter_column('sponsor',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
